name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  testbashversion:
    runs-on: ubuntu-latest
    steps:
      - run: cd ./src/webapp
      - run: npm install
      - run: npm run start-server
      - run: cd ../../e2e/cypress
      - run: npm install
      - run: npm run test

