name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  testbashversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd src/webapp
      - run: npm install
      - run: npm run start-server
      - run: cd ../../e2e/cypress
      - run: npm install
      - run: npm run test

